### ISSUE TITLE
update of code to use the new attribute to check for the availability of MPS

### ISSUE THREAD

**Issue by ghost** [jeffheaton/app_deep_learning#2]
When I try to install pytorch, at the end I want to check if everything is alright using the pytorch-install-aug-2023.ipynb.
But I received a warning:
<img width="1162" alt="image" src="https://github.com/jeffheaton/app_deep_learning/assets/84087309/c07b24b9-8138-4dda-b396-f5f24af79cda">
Maybe 'has_mps'  has been replaced by 'torch.backends.mps.is_built()'?

**Comment by jeffheaton** [comment]
Thanks, let me check into that! Looks like a more logical name...

**Comment by alexandriabindas** [comment]
@jeffheaton  @wendy-ziwen-meng I ran into the same thing. This change worked perfectly for me: 

```python
has_mps = torch.backends.mps.is_built()
device = "mps" if has_mps else "gpu" if torch.cuda.is_available() else "cpu"
```

**Comment by jeffheaton** [comment]
Correct code for this seems to be: (see issue #6)

`
# Make use of a GPU or MPS (Apple) if one is available.
has_mps = torch.backends.mps.is_built()
device = "mps" if has_mps else "cuda" if torch.cuda.is_available() else "cpu"
print(f"Using device: {device}")
`
This works on CUDA as well.

**Comment by jeffheaton** [comment]
Okay, I think I got every location where device is detected, if there are any more, let me know.
