### ISSUE TITLE
Inside notebook t81_558_class_05_4_generators. A link to be changed?

### ISSUE THREAD

**Issue by lucapug** [jeffheaton/app_deep_learning#4]
There is a link to ImageDatagenerator  in the notebook https://github.com/jeffheaton/app_deep_learning/blob/main/t81_558_class_05_4_generators.ipynb, which still points to a Keras page. However, in the subsequent lines of code, you make use of Pytorch transforms from torchvision for image augmentation examples.

**Comment by jeffheaton** [comment]
Thanks!
