### ISSUE TITLE
Kernal naming and installation housekeeping

### ISSUE THREAD

**Issue by Dimantarian** [jeffheaton/app_deep_learning#5]
- Update kernel registration in pytorch-install-aug-2023.ipynb based on the yml files.

- Noticed that the torch-conda.yml for mac still uses 3.9, but others are 3.11. suggest upgrading and renaming file to torch-m-series.yml?

- pytorch-install-aug-2023.ipynb is duplicated in the top directory and in the install folder, suggest removing from top directory

Change from:

python -m ipykernel install --user --name pytorch --display-name "Python 3.9 (torch)"

to:

python -m ipykernel install --user --name pytorch --display-name "Python 3.11 (torch)"

**Comment by jeffheaton** [comment]
Thanks!
