### ISSUE TITLE
t81_558_class_10_4_seasonal.ipynb: name 'cnn_history' is not defined

### ISSUE THREAD

**Issue by sascharo** [jeffheaton/app_deep_learning#9]
Where is `cnn_history` coming from? It's used in your notebook but is not defined and throws an error.

[github.com/jeffheaton/app_deep_learning/blob/main/t81_558_class_10_4_seasonal.ipynb](https://github.com/jeffheaton/app_deep_learning/blob/main/t81_558_class_10_4_seasonal.ipynb)

**Comment by jeffheaton** [comment]
Thanks, that was some hold over code from the TensorFlow version.
